name: Latest

on: [push, pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn install --frozen-lockfile
    - run: npm test
      env:
        CI: true
